"""add widgets colour

Revision ID: bbbb11112222
Revises: ef104e2e9cf3

Generated by scripts/make_scenario.sh for the 'two-heads' scenario.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bbbb11112222'
down_revision: Union[str, None] = 'ef104e2e9cf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("widgets", sa.Column("colour", sa.String(length=20), nullable=True))


def downgrade() -> None:
    pass
