"""add orders placed at

Revision ID: race0000aaaa
Revises: 9d7d12606351

Generated by scripts/make_scenario.sh for the 'race-a' scenario.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'race0000aaaa'
down_revision: Union[str, None] = '9d7d12606351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("orders", sa.Column("placed_at", sa.DateTime, nullable=True))


def downgrade() -> None:
    pass
