#!/usr/bin/env bash
# Create a branch that reproduces one migration failure mode, ready to push
# as a PR so you can watch the gate behave on real GitHub infrastructure.
#
# Usage:  scripts/make_scenario.sh <scenario>
#
# Scenarios and what each should do:
#
#   healthy          a normal new migration on top of the head
#                      -> Check A pass, Check B pass, merge allowed
#   two-heads        a migration forked from an older parent
#                      -> Check A FAIL (Part 1)
#   delete-head      remove the current head's file
#                      -> Check A pass (silently!), Check B FAIL (Part 7 Case A)
#   delete-middle    remove a middle node, children left pointing at it
#                      -> Check A FAIL, clean diagnosis (Part 7 Case B)
#   rename-id        rename a file AND change the revision id inside
#                      -> Check B FAIL — changing an id is deleting one
#   rename-cosmetic  rename a file but keep the revision id inside
#                      -> everything PASS — proves we don't false-positive
#
set -euo pipefail

cd "$(dirname "$0")/.."

ROOT_REV="ef104e2e9cf3"    # create widgets table  (root)
MID_REV="8835ab9cf385"     # add widgets.sku       (middle node)
HEAD_REV="9d7d12606351"    # create orders table   (current head)

VDIR="alembic/versions"
SCENARIO="${1:-}"

usage() {
  sed -n '3,25p' "$0" | sed 's/^# \{0,1\}//'
  exit 1
}
[[ -n "$SCENARIO" ]] || usage

BRANCH="scenario/${SCENARIO}"

# Always build the scenario from a clean main.
git checkout -q main
git branch -D "$BRANCH" 2>/dev/null || true
git checkout -qb "$BRANCH"

file_for() { ls "$VDIR/$1"_*.py; }

new_migration() {
  # new_migration <new_id> <down_revision> <slug> <body>
  local id="$1" down="$2" slug="$3" body="$4"
  cat > "$VDIR/${id}_${slug}.py" <<EOF
"""${slug//_/ }

Revision ID: ${id}
Revises: ${down}

Generated by scripts/make_scenario.sh for the '${SCENARIO}' scenario.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '${id}'
down_revision: Union[str, None] = '${down}'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    ${body}


def downgrade() -> None:
    pass
EOF
}

case "$SCENARIO" in
  healthy)
    new_migration "aaaa11112222" "$HEAD_REV" "add_orders_total" \
      'op.add_column("orders", sa.Column("total", sa.Numeric(10, 2), nullable=True))'
    MSG="feat: add orders.total (healthy — should pass every check)"
    ;;

  two-heads)
    # Forked from the ROOT rather than the head: two people branching from
    # the same commit, exactly as in the doc's Figure 1.
    new_migration "bbbb11112222" "$ROOT_REV" "add_widgets_colour" \
      'op.add_column("widgets", sa.Column("colour", sa.String(length=20), nullable=True))'
    MSG="feat: add widgets.colour (forked from root -> TWO HEADS)"
    ;;

  delete-head)
    git rm -q "$(file_for "$HEAD_REV")"
    MSG="chore: delete the current head migration (Part 7 Case A)"
    ;;

  delete-middle)
    git rm -q "$(file_for "$MID_REV")"
    MSG="chore: delete a middle-node migration (Part 7 Case B)"
    ;;

  rename-id)
    src="$(file_for "$HEAD_REV")"
    dst="$VDIR/cccc11112222_create_orders_table.py"
    git mv "$src" "$dst"
    # Change the id INSIDE the file too — this is what makes it a deletion.
    sed -i.bak "s/^revision: str = '${HEAD_REV}'/revision: str = 'cccc11112222'/" "$dst"
    rm -f "${dst}.bak"
    MSG="chore: rename head migration AND change its id (should FAIL Check B)"
    ;;

  rename-cosmetic)
    src="$(file_for "$HEAD_REV")"
    dst="$VDIR/${HEAD_REV}_create_orders_table_renamed.py"
    git mv "$src" "$dst"
    # revision id inside is untouched, so nothing has actually vanished.
    MSG="chore: rename head migration file only, id unchanged (should PASS)"
    ;;

  *)
    echo "unknown scenario: $SCENARIO" >&2
    usage
    ;;
esac

git add -A
git commit -qm "$MSG"

echo
echo "=================================================================="
echo " branch:   $BRANCH"
echo " commit:   $MSG"
echo "=================================================================="
echo
echo "Run the checks locally:"
echo "    python3 .github/actions/check-migrations/check_heads.py alembic.ini"
echo "    bash .github/actions/check-migrations/check_ids.sh $VDIR main"
echo
echo "Or push it and open a PR to watch the gate on GitHub:"
echo "    git push -u origin $BRANCH"
echo "    # then open a PR against main in the GitHub UI"
echo
echo "Back to a clean tree with:  git checkout main"
