#!/usr/bin/env bash
# Create a branch that reproduces one migration failure mode, ready to push
# as a PR so you can watch the gate behave on real GitHub infrastructure.
#
# Usage:  scripts/make_scenario.sh <scenario>
#
# Scenarios and what each should do:
#
#   healthy          a normal new migration on top of the head
#                      -> Check A pass, Check B pass, merge allowed
#   two-heads        a migration forked from an older parent
#                      -> Check A FAIL (Part 1)
#   delete-head      remove the current head's file
#                      -> Check A pass (silently!), Check B FAIL (Part 7 Case A)
#   delete-middle    remove a middle node, children left pointing at it
#                      -> Check A FAIL, clean diagnosis (Part 7 Case B)
#   rename-id        rename a file AND change the revision id inside
#                      -> Check B FAIL — changing an id is deleting one
#   rename-cosmetic  rename a file but keep the revision id inside
#                      -> everything PASS — proves we don't false-positive
#   race-a / race-b  two branches, each valid ALONE, that conflict only
#                    once both are merged
#                      -> each PASSES on its own; the pair breaks main
#                      -> see scripts/demo_race.sh
#
set -euo pipefail

cd "$(dirname "$0")/.."

ROOT_REV="ef104e2e9cf3"    # create widgets table  (root)
MID_REV="8835ab9cf385"     # add widgets.sku       (middle node)
HEAD_REV="9d7d12606351"    # create orders table   (current head)

VDIR="alembic/versions"
SCENARIO="${1:-}"

usage() {
  sed -n '3,25p' "$0" | sed 's/^# \{0,1\}//'
  exit 1
}
[[ -n "$SCENARIO" ]] || usage

BRANCH="scenario/${SCENARIO}"

# Refuse to run with uncommitted work in the tree. This script commits the
# breakage it creates, and an earlier version used `git add -A` — which
# silently swept unrelated in-progress edits onto a scenario branch and off
# main. Bailing out here is the fix; the commit below is also now scoped to
# the versions directory only.
if [[ -n "$(git status --porcelain --untracked-files=normal)" ]]; then
  echo "error: working tree is not clean — commit or stash first." >&2
  echo >&2
  git status --short >&2
  exit 1
fi

# Always build the scenario from a clean main.
git checkout -q main
git branch -D "$BRANCH" 2>/dev/null || true
git checkout -qb "$BRANCH"

file_for() { ls "$VDIR/$1"_*.py; }

new_migration() {
  # new_migration <new_id> <down_revision> <slug> <body>
  local id="$1" down="$2" slug="$3" body="$4"
  cat > "$VDIR/${id}_${slug}.py" <<EOF
"""${slug//_/ }

Revision ID: ${id}
Revises: ${down}

Generated by scripts/make_scenario.sh for the '${SCENARIO}' scenario.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '${id}'
down_revision: Union[str, None] = '${down}'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    ${body}


def downgrade() -> None:
    pass
EOF
}

case "$SCENARIO" in
  healthy)
    new_migration "aaaa11112222" "$HEAD_REV" "add_orders_total" \
      'op.add_column("orders", sa.Column("total", sa.Numeric(10, 2), nullable=True))'
    MSG="feat: add orders.total (healthy — should pass every check)"
    ;;

  two-heads)
    # Forked from the ROOT rather than the head, so this branch has two
    # heads all by itself and fails in isolation. Not the same thing as the
    # race below.
    new_migration "bbbb11112222" "$ROOT_REV" "add_widgets_colour" \
      'op.add_column("widgets", sa.Column("colour", sa.String(length=20), nullable=True))'
    MSG="feat: add widgets.colour (forked from root -> TWO HEADS)"
    ;;

  # ---- the staleness race: race-a and race-b -------------------------------
  # Each of these branches from the CURRENT HEAD, so each has exactly one
  # head and passes every check on its own. They only conflict once BOTH
  # are merged, because they then become two children of the same parent.
  #
  # This is the case a pull-request check cannot catch by itself: both PRs
  # are genuinely correct when tested, and merging the first does not
  # re-run the second's check. Closing it needs either "require branches to
  # be up to date before merging" or a merge queue.
  #
  # Prove it locally with: bash scripts/demo_race.sh
  race-a)
    new_migration "race0000aaaa" "$HEAD_REV" "add_orders_placed_at" \
      'op.add_column("orders", sa.Column("placed_at", sa.DateTime, nullable=True))'
    MSG="feat: add orders.placed_at (valid alone — half of the race)"
    ;;

  race-b)
    new_migration "race0000bbbb" "$HEAD_REV" "add_orders_status" \
      'op.add_column("orders", sa.Column("status", sa.String(length=20), nullable=True))'
    MSG="feat: add orders.status (valid alone — other half of the race)"
    ;;

  delete-head)
    git rm -q "$(file_for "$HEAD_REV")"
    MSG="chore: delete the current head migration (Part 7 Case A)"
    ;;

  delete-middle)
    git rm -q "$(file_for "$MID_REV")"
    MSG="chore: delete a middle-node migration (Part 7 Case B)"
    ;;

  rename-id)
    src="$(file_for "$HEAD_REV")"
    dst="$VDIR/cccc11112222_create_orders_table.py"
    git mv "$src" "$dst"
    # Change the id INSIDE the file too — this is what makes it a deletion.
    sed -i.bak "s/^revision: str = '${HEAD_REV}'/revision: str = 'cccc11112222'/" "$dst"
    rm -f "${dst}.bak"
    MSG="chore: rename head migration AND change its id (should FAIL Check B)"
    ;;

  rename-cosmetic)
    src="$(file_for "$HEAD_REV")"
    dst="$VDIR/${HEAD_REV}_create_orders_table_renamed.py"
    git mv "$src" "$dst"
    # revision id inside is untouched, so nothing has actually vanished.
    MSG="chore: rename head migration file only, id unchanged (should PASS)"
    ;;

  *)
    echo "unknown scenario: $SCENARIO" >&2
    usage
    ;;
esac

# Scoped to the versions directory rather than `git add -A`, so this can
# never pick up anything the scenario didn't create.
git add -A -- "$VDIR"
git commit -qm "$MSG"

echo
echo "=================================================================="
echo " branch:   $BRANCH"
echo " commit:   $MSG"
echo "=================================================================="
echo
echo "Run the checks locally:"
echo "    python3 .github/actions/check-migrations/check_heads.py alembic.ini"
echo "    bash .github/actions/check-migrations/check_ids.sh $VDIR main"
echo
echo "Or push it and open a PR to watch the gate on GitHub:"
echo "    git push -u origin $BRANCH"
echo "    # then open a PR against main in the GitHub UI"
echo
echo "Back to a clean tree with:  git checkout main"
